grails-app/controllers/eu/hulboj/FlatController.groovy
package eu.hulboj



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class FlatController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]
    def paramService

    def welcome() {
        flash.message = "fffff"
        paramService.setMenuSelector(ParamService.MenuSelector.start)
        render (view: "welcome", model: [flaga: false])
    }

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Flat.list(params), model:[flatInstanceCount: Flat.count()]
    }

    def show(Home flatInstance) {
        respond flatInstance
    }

    def create() {
        respond new Home(params)
    }

    @Transactional
    def save(Home flatInstance) {
        if (flatInstance == null) {
            notFound()
            return
        }

        if (flatInstance.hasErrors()) {
            respond flatInstance.errors, view:'create'
            return
        }

        flatInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'flat.label', default: 'Flat'), flatInstance.id])
                redirect flatInstance
            }
            '*' { respond flatInstance, [status: CREATED] }
        }
    }

    def edit(Home flatInstance) {
        respond flatInstance
    }

    @Transactional
    def update(Home flatInstance) {
        if (flatInstance == null) {
            notFound()
            return
        }

        if (flatInstance.hasErrors()) {
            respond flatInstance.errors, view:'edit'
            return
        }

        flatInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Flat.label', default: 'Flat'), flatInstance.id])
                redirect flatInstance
            }
            '*'{ respond flatInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Home flatInstance) {

        if (flatInstance == null) {
            notFound()
            return
        }

        flatInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Flat.label', default: 'Flat'), flatInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'flat.label', default: 'Flat'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/flat/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'flat.label', default: 'Flat')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-flat" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-flat" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${flatInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${flatInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:flatInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/flat/index.gsp
<%@ page import="eu.hulboj.Home" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'flat.label', default: 'Flat')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-flat" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-flat" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<th><g:message code="flat.address.label" default="Address" /></th>
					
						<g:sortableColumn property="name" title="${message(code: 'flat.name.label', default: 'Name')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${flatInstanceList}" status="i" var="flatInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${flatInstance.id}">${fieldValue(bean: flatInstance, field: "address")}</g:link></td>
					
						<td>${fieldValue(bean: flatInstance, field: "name")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${flatInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/flat/welcome.gsp
<%--
  Created by IntelliJ IDEA.
  User: hulborad
  Date: 2015-09-15
  Time: 12:01
--%>

<%@ page import="eu.hulboj.Home" %>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name="layout" content="welcomedec">
  <asset:javascript src="application.js"/>
</head>

<body>
    <!-- Jumbotron -->
    <div class="jumbotron">
        <h1>System rejestracji</h1>
        <p class="lead"><g:message code="page.welcome.main.info" default="System jest dla osób wynajmujacych mieszkanie. Właściciel Radoslaw H."/> </p>
        <p><a class="btn btn-lg btn-success" href="#" role="button"><g:message code="page.welcome.see.you" default="Warto zobaczyć"/></a></p>
        <p><g:generateLink/></p>
    </div>
</body>
</html>