grails-app/controllers/eu/hulboj/AgreementController.groovy
package eu.hulboj

import org.joda.time.DateTime
import org.joda.time.format.DateTimeFormat
import org.springframework.web.multipart.commons.CommonsMultipartFile


class AgreementController {

    AgreementService agreementService

    static String PATTERN = "MM/dd/yyyy"

    def save() {

        DateTime startDate = getStartDate(params.startDate_value)
        DateTime endDate = getEndDate(params.endDate_value)
        File file = getFile(params.file)

        try {
            agreementService.saveAgreement(startDate, endDate, file)
        } catch (Exception ex) {
            String errorMessage = ex.toString()
            flash.serverError = errorMessage
            log.error(errorMessage)
        }
        redirect(controller: "configurator", action: "configure")
    }

    File getFile(CommonsMultipartFile multipartFile) {
        File file = null
        try {
            file = new File(multipartFile.getOriginalFilename())
            multipartFile.transferTo(file)

        } catch (Exception ex) {
            log.info("No file selected" + ex.toString())
        }
        file
    }

    DateTime getEndDate(String endDate) {
        DateTime.parse(endDate, DateTimeFormat.forPattern(PATTERN))
    }

    DateTime getStartDate(String startDate) {
        DateTime.parse(startDate, DateTimeFormat.forPattern(PATTERN))
    }
}

grails-app/controllers/eu/hulboj/ConfiguratorController.groovy
package eu.hulboj

class ConfiguratorController {

	def paramService
	
    def index() { }
	
	def configure() {
		def status = params.serverStatus
		paramService.setMenuSelector(ParamService.MenuSelector.configurator)
		render(view: "flat", model: [flaga: false, status: status])
	}
}

grails-app/views/configurator/_createAgreement.gsp
<g:uploadForm name="postAgreementForm" controller="agreement" action="save" onsubmit="disableMediaFileUpload();" class="form-horizontal" data-target="#postStatus">
<g:hiddenField name="link" value="${postMsgInstance?.link}"/>
<fieldset>
    <g:if test="${params.serverStatus == "500"}">
        <g:if test="${flash.serverError}">
            <div class="alert alert-error" style="display: block">${flash.serverError}</div>
        </g:if>
    </g:if>
    <g:else>
        <div class="panel-body">
            <calendar:resources lang="en" theme="tiger"/>
            <div class="col-xs-6">
                <div class="form-group" >
                    <label for="startDate" class="control-label col-xs-3">Start date:</label>
                    <div class="col-xs-9">
                        <calendar:datePicker style="height: 100%" class="form-control" name="startDate"
                                             years="${2014..2017}" value="${new Date()}"
                                             defaultValue="${new Date()}"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="endDate" class="control-label col-xs-3">End date:</label>
                    <div class="col-xs-9">
                        <calendar:datePicker style="width: 100%; height: 100%" class="form-control" name="endDate"
                                             years="${2014..2017}" value="${new Date()}"
                                             defaultValue="${new Date()}"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="file" class="control-label col-xs-3">File:</label>
                    <div class="col-xs-9" >
                        <input style="height: 0%" class="form-control" type='file' size="22" value="" default="ddd" name='file'/>
                    </div>
                </div>
            </div>
            <div class="col-xs-6">
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </div>
    </g:else>


</fieldset>
</g:uploadForm>

grails-app/views/configurator/_createFactor.gsp
<div class="panel panel-default">
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-3">
                <span class="label label-default">Create</span>
                <div class="row-lg-3">
                    <div class="input-group">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">Name:</button>
                        </span>
                        <input type="text" class="form-control" placeholder="name...">
                        <!--http://www.eyecon.ro/bootstrap-datepicker/# -->
                    </div>
                </div>
                <g:spaceBr count="1"/>
                <span class="label label-default">Create</span>
                <div class="row-lg-3">
                    <div class="input-group">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">Unit:</button>
                        </span>
                        <input type="text" class="form-control" placeholder="unit...">
                    </div>
                </div>
                <g:spaceBr count="1"/>
                <span class="label label-default">Create</span>
                <div class="row-lg-3">
                    <div class="input-group">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">Price:</button>
                        </span>
                        <input type="text" class="form-control" placeholder="price...">
                    </div>
                </div>
            </div>
            <div class="col-lg-3">
                <g:spaceBr count="1" />
                <div class="row-lg-3">
                    <div class="input-group">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">Add</button>
                            <button class="btn btn-default" type="button">Save</button>
                        </span>
                        <button class="btn btn-default" type="button">Cancel</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

grails-app/views/configurator/_createPanel.gsp
<div id="tabPanelDiv">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Agreement</a></li>
        <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Provider</a></li>
        <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Factor</a></li>
    </ul>
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="home"><g:render template="createAgreement"/></div>
        <div role="tabpanel" class="tab-pane" id="profile"><g:render template="createProvider"/></div>
        <div role="tabpanel" class="tab-pane" id="messages"><g:render template="createFactor"/></div>
    </div>
    <div id="postStatus"/>
</div>

grails-app/views/configurator/_createProvider.gsp
<div class="panel panel-default">
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-3">
                <span class="label label-default">Create</span>
                <div class="row-lg-3">
                    <div class="input-group">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">Name:</button>
                        </span>
                        <input type="text" class="form-control" placeholder="name...">
                        <!--http://www.eyecon.ro/bootstrap-datepicker/# -->
                    </div>
                </div>
                <g:spaceBr count="1"/>
                <span class="label label-default">Create</span>
                <div class="row-lg-3">
                    <div class="input-group">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">Address:</button>
                        </span>
                        <input type="text" class="form-control" placeholder="address...">
                    </div>
                </div>
            </div>
            <div class="col-lg-3">
                <g:spaceBr count="1" />
                <div class="row-lg-3">
                    <div class="input-group">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">Save</button>
                        </span>
                        <button class="btn btn-default" type="button">Cancel</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

grails-app/views/configurator/flat.gsp
<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<meta name="layout" content="welcomedec">
<title>Insert title here</title>
</head>
<body>
  <div class="body">
    <h2>Configurator</h2>
    <p id="selectedTown" class="lead">Choose the town to create agreement.</p>
    <g:render template="/template/dropdown"/>
    <g:spaceBr count="1"/>
    <g:render template="createPanel"/>
    <g:spaceBr count="3"/>
  </div>
</body>
</html>