grails-app/domain/eu/hulboj/FlatCalculator.groovy
package eu.hulboj


class FlatCalculator {

    List<Home> flats
    static hasMany = [flats: Home]
    static constraints = {
    }
}

grails-app/controllers/eu/hulboj/FlatCalculatorController.groovy
package eu.hulboj

import eu.hulboj.form.Amount

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class FlatCalculatorController  {

    FlatCalculator flatCalculator
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def paramService

    /*This will be request from the client*/
    def flatList() {
      def billList = []
      render(template: "flatTemplates/factorTable", model: [billList: billList])
    }

    def flat() {
        paramService.setMenuSelector(ParamService.MenuSelector.flat)
        def billList = Amount.findAll()
        render(view: "flat", model: [flaga: false, billList: billList])
    }

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond FlatCalculator.list(params), model:[flatCalculatorInstanceCount: FlatCalculator.count()]
    }

    def show(FlatCalculator flatCalculatorInstance) {
        respond flatCalculatorInstance
    }

    def create() {
        respond new FlatCalculator(params)
    }

    @Transactional
    def save(FlatCalculator flatCalculatorInstance) {
        if (flatCalculatorInstance == null) {
            notFound()
            return
        }

        if (flatCalculatorInstance.hasErrors()) {
            respond flatCalculatorInstance.errors, view:'create'
            return
        }

        flatCalculatorInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'flatCalculator.label', default: 'FlatCalculator'), flatCalculatorInstance.id])
                redirect flatCalculatorInstance
            }
            '*' { respond flatCalculatorInstance, [status: CREATED] }
        }
    }

    def edit(FlatCalculator flatCalculatorInstance) {
        respond flatCalculatorInstance
    }

    @Transactional
    def update(FlatCalculator flatCalculatorInstance) {
        if (flatCalculatorInstance == null) {
            notFound()
            return
        }

        if (flatCalculatorInstance.hasErrors()) {
            respond flatCalculatorInstance.errors, view:'edit'
            return
        }

        flatCalculatorInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'FlatCalculator.label', default: 'FlatCalculator'), flatCalculatorInstance.id])
                redirect flatCalculatorInstance
            }
            '*'{ respond flatCalculatorInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(FlatCalculator flatCalculatorInstance) {

        if (flatCalculatorInstance == null) {
            notFound()
            return
        }

        flatCalculatorInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'FlatCalculator.label', default: 'FlatCalculator'), flatCalculatorInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'flatCalculator.label', default: 'FlatCalculator'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/flatCalculator/_form.gsp
<%@ page import="eu.hulboj.FlatCalculator" %>



<div class="fieldcontain ${hasErrors(bean: flatCalculatorInstance, field: 'factors', 'error')} ">
	<label for="factors">
		<g:message code="flatCalculator.factors.label" default="Factors" />
		
	</label>
	

</div>

grails-app/views/flatCalculator/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'flatCalculator.label', default: 'FlatCalculator')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-flatCalculator" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-flatCalculator" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${flatCalculatorInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${flatCalculatorInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:flatCalculatorInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/flatCalculator/edit.gsp
<%@ page import="eu.hulboj.FlatCalculator" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'flatCalculator.label', default: 'FlatCalculator')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-flatCalculator" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-flatCalculator" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${flatCalculatorInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${flatCalculatorInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:flatCalculatorInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${flatCalculatorInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/flatCalculator/flat.gsp
<%--
  Created by IntelliJ IDEA.
  User: hulborad
  Date: 2015-09-15
  Time: 12:01
--%>

<%@ page import="eu.hulboj.FlatCalculator" %>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="layout" content="welcomedec">

    <asset:javascript src="/flat/collectorBill.js"/>
    <asset:javascript src="/flat/clientBill.js"/>

</head>

<body>
<parameter name="selector" value="flat"/>

<g:render template="flatTemplates/insertBill"/>
<g:render template="flatTemplates/factorTable" model="[billList: billList]"/>

</body>
</html>

grails-app/views/flatCalculator/index.gsp
<%@ page import="eu.hulboj.FlatCalculator" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'flatCalculator.label', default: 'FlatCalculator')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-flatCalculator" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-flatCalculator" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${flatCalculatorInstanceList}" status="i" var="flatCalculatorInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${flatCalculatorInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/flatCalculator/show.gsp
<%@ page import="eu.hulboj.FlatCalculator" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'flatCalculator.label', default: 'FlatCalculator')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-flatCalculator" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-flatCalculator" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list flatCalculator">
			
				<g:if test="${flatCalculatorInstance?.factors}">
				<li class="fieldcontain">
					<span id="factors-label" class="property-label"><g:message code="flatCalculator.factors.label" default="Factors" /></span>
					
						<span class="property-value" aria-labelledby="factors-label"><g:fieldValue bean="${flatCalculatorInstance}" field="factors"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:flatCalculatorInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${flatCalculatorInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>